image: centos:latest

before_script:
    # add epel-repo to centos
    - yum install -y epel-release
    - yum update -y

    # install dependencies
    - yum install -y rabbitmq-server redis python34 python34-pip python34-devel readline-devel R
    - pip3 install -e . --default-timeout=180
    - R -e 'source("https://bioconductor.org/biocLite.R"); biocLite(); biocLite("limma")'

    # start services
    - redis-server --daemonize yes
    - rabbitmq-server -detached
    - celery worker -A fractalis:celery -D -l info

test:
    script:
        - python setup.py test
