image: python:latest

services:
    - redis:latest
    - rabbitmq:latest

before_script:
    - pip install -e .
    - pip install flake8
    - redis-server

test:
    script:
        - export FRACTALIS_MODE="testing"
        - python setup.py test
        - flake8 .
