image: python:3

before_script:
    - pip install -e .

test:
    script:
        - echo $PYTHONPATH
        - export PYTHONPATH=/usr/lib/python3.5
        - export FRACTALIS_MODE="testing"
        - python setup.py test
