image: python:latest

services:
    - redis-server
    - rabbitmq

before_script:
    - pip install -e .
    - pip install flake8

test:
    script:
        - export FRACTALIS_MODE="testing"
        - python setup.py test
        - flake8 .
