image: python:latest

services:
    - redis:latest

before_script:
    - pip install -e .
    - pip install flake8
    
connect:
    - image: redis
    - script:
        - redis-cli -h redis PING

test:
    script:
        - export FRACTALIS_MODE="testing"
        - python setup.py test
        - flake8 .
