image: python:latest

services:
    - redis
    - rabbitmq

before_script:
    - pip install -e .
    - pip install flake8
    - export FRACTALIS_CONFIG="$(pwd)/gitlab-config.py"
    - celery worker -A fractalis.celery -D -l info

test:
    script:
        - python setup.py test
        - flake8 .
