image: python:3

before_script:
    - pip install coverage
    - apt-get update && apt-get install -y python3-dev
    - pip install -e .

test:
    script:
        - export FRACTALIS_MODE="testing"
        - coverage run --source=fractalis setup.py test
        - coverage report --show-missing
