image: python:latest

services:
    - redis

before_script:
    - pip install -e .
    - pip install flake8
    - echo "REDIS_HOST='redis'" > /root/conf.py
    - echo "CELERY_RESULT_BACKEND='redis://redis:6379'" >> /root/conf.py
    - export FRACTALIS_CONFIG=/root/conf.py
    - apt-get install rabbitmq-server
    - rabbitmq-server
    - celery worker -A fractalis.celery -b rabbit

test:
    script:
        - python setup.py test
        - flake8 .
