image: python:latest

services:
    - redis
    - rabbitmq

before_script:
    - apt-get install r-base r-bioc-limma
    - pip install -e . --default-timeout=180
    - pip install flake8
    - export FRACTALIS_CONFIG="$(pwd)/gitlab-config.py"
    - celery worker -A fractalis:celery -D -l info

test:
    script:
        - python setup.py test