image: python:3

before_script:
    - pip install -e .

test:
    script:
        - export PYTHONPATH=$PWD/install/site-packages
        - export FRACTALIS_MODE="testing"
        - python setup.py test
