variables:
    PYPI_USER: SECURE
    PYPI_PASS: SECURE
    DOCKER_USER: SECURE
    DOCKER_PASS: SECURE
    DOCKER_IMAGE_TAG: fractalis:$CI_COMMIT_TAG
    SDIST: fractalis-$CI_COMMIT_TAG.tar.gz

stages:
    - build_sdist
    - build_image
    - test
    - release

build:sdist:
  stage: build_sdist
  image: python:3.6-alpine
  script:
      - python3 setup.py sdist
  artifacts:
      paths:
          - dist/$SDIST

build:image:
  stage: build_image
  image: docker:dind
  script:
      - docker build -t $DOCKER_IMAGE_TAG --build-arg SDIST=$SDIST .
      - docker save $DOCKER_IMAGE_TAG -o image.tar
  dependencies:
      - build:sdist
  artifacts:
      paths:
          - image.tar

test:
    stage: test
    image: docker:dind
    services:
        - redis:3.2-alpine
        - rabbitmq:3.7-alpine
    script:
        - docker load -i image.tar
        - >
          docker run fractalis:$CI_COMMIT_TAG
          -e REDIS_HOST=redis -e RABBITMQ_HOST=rabbitmq
          sh -c "celery worker -D -A fractalis:celery
                && pip3 install -r requirements.txt
                && flake8
                && pytest tests"
    dependencies:
        - build:image

release:pypi:
    stage: release
    image: python:3.6-alpine
    script:
        - pip3 install twine
        - twine upload dist/$SDIST -u $PYPI_USER -p $PYPI_PASS
    dependencies:
        - build:sdist
    only:
        - tags

release:docker:
    stage: release
    image: docker:dind
    script:
        - docker load -i image.tar
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push $DOCKER_IMAGE_TAG
    dependencies:
        - build:image
    only:
        - tags