image: python:latest

services:
    - redis
    - rabbitmq

before_script:
    - pip install -e .
    - pip install flake8
    - echo "REDIS_HOST=redis" > fractalis.conf
    - export FRACTALIS_CONFIG=fractalis.conf
    
test:
    script:
        - python setup.py test
        - flake8 .
