image: centos:latest

variables:
    PYPI_USER: SECURE
    PYPI_PASSWORD: SECURE

stages:
    - setup
    - test
    - publish
    - cleanup

install_deps:
    stage: setup
    script:
        - yum install -y epel-release
        - yum update -y
        - yum install -y rabbitmq-server redis python34 python34-pip python34-devel readline-devel R
        - pip3 install -e . -i https://pypi.lcsb.uni.lu/simple
        - pip3 install -r requirements.txt -i https://pypi.lcsb.uni.lu/simple
        - R -e 'source("https://bioconductor.org/biocLite.R"); biocLite(); biocLite("limma")'

tests:
    stage: test
    script:
        - redis-server --daemonize yes
        - rabbitmq-server -detached
        - celery worker -A fractalis:celery -D -l info
        - python3 setup.py test
        - flake8
    dependencies:
        - install_deps

release:
    stage: publish
    script:
        - echo "[server-login]" > ~/.pypirc
        - echo "username=" ${PYPI_USER} >> ~/.pypirc
        - echo "password=" ${PYPI_PASSWORD} >> ~/.pypirc
        - python3 setup.py check sdist upload
    only:
        - tags
    except:
        - branches
    dependencies:
        - install_deps

rm_secrets:
    stage: cleanup
    when: always
    script:
        - rm -f ~/.pypirc
