image: centos:latest

services:
    - redis:3.2-alpine
    - rabbitmq:3.7-alpine


variables:
    PYPI_USER: SECURE
    PYPI_PASS: SECURE
    DOCKER_USER: SECURE
    DOCKER_PASS: SECURE
    DOCKER_IMAGE_TAG: fractalis:$CI_COMMIT_TAG
    SDIST: fractalis-$CI_COMMIT_TAG.tar.gz

stages:
    - prepare
    - build
    - test
    - release

prepare:
  stage: prepare
  script:
      - yum install -y epel-release
      - yum update -y
      - yum install -y \
        python34 \
        python34-pip \
        yum-utils \
        device-mapper-persistent-data \
        lvm2
      - yum-config-manager \
        --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      - yum install -y docker-ce
      - systemctl start docker
      - pip3 install twine
  artifacts:
      untracked: true

build:
  stage: build
  script:
      - python3 setup.py sdist
      - docker build -t $DOCKER_IMAGE_TAG --build-arg SDIST=$SDIST .
      - docker save $DOCKER_IMAGE_TAG -o image.tar
  artifacts:
      paths:
          - dist/$SDIST
          - image.tar

test:
    stage: test
    script:
        - docker load -i image.tar
        - >
          docker run fractalis:$CI_COMMIT_TAG
          -e REDIS_HOST=redis -e RABBITMQ_HOST=rabbitmq
          sh -c "celery worker -D -A fractalis:celery
                && pip3 install -r requirements.txt
                && flake8
                && pytest tests"

release:pypi:
    stage: release
    script:
        - twine upload dist/$SDIST -u $PYPI_USER -p $PYPI_PASS
    only:
        - tags

release:docker:
    stage: release
    script:
        - docker load -i image.tar
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push $DOCKER_IMAGE_TAG
    only:
        - tags