FROM buildpack-deps:stretch

WORKDIR /app
COPY . /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		r-base \
		python3.5 \
		python3.5-dev \
		python3-pip \
		python3-setuptools \
		r-bioc-limma
RUN pip3 install wheel
RUN pip3 install -e /app --default-timeout 180

CMD ["celery", "worker", "-A", "fractalis:celery"]
