version: '3.3'
services:
    redis:
        image: 'redis:alpine'
        command: >
            sh -c "redis-server
            && redis-cli CONFIG SET maxmemory 4gb
            && redis-cli CONFIG SET maxmemory-policy allkeys-lru"
    rabbitmq:
        image: 'rabbitmq:alpine'
    app:
        image: 'sherzinger/fractalis:0.5.3'
        volumes:
            - ./config/fractalis/config.py:/config.py
        environment:
            - FRACTALIS_CONFIG=/config.py
        command: gunicorn -w 3 -b :5000 --log-file gunicorn.log fractalis:app
        expose:
            - '5000'
        depends_on:
            - redis
            - rabbitmq
    worker:
        image: 'sherzinger/fractalis:0.5.3'
        volumes:
            - ./config/fractalis/config.py:/config.py
        environment:
            - FRACTALIS_CONFIG=/config.py
        command: celery worker -A fractalis:celery -l info --autoscale 16,4
        depends_on:
            - redis
            - rabbitmq
    nginx:
        image: 'nginx:alpine'
        volumes:
            - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./config/nginx/html:/usr/share/nginx/html
            - ./config/nginx/certs/server.crt:/etc/nginx/server.crt
            - ./config/nginx/certs/server.key:/etc/nginx/server.key
        ports:
            - ${FRACTALIS_HTTP_PORT:-80}:80
            - ${FRACTALIS_HTTPS_PORT:-443}:443
        depends_on:
            - app
