version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  default:
    class: logging.handlers.TimedRotatingFileHandler
    level: WARNING
    formatter: default
    filename: fractalis.log
    when: midnight
    backupCount: 14
    encoding: utf8
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default

root:
    level: INFO
    handlers: [default, console]
fractalis:
  Flask:
    level: INFO
    handlers: [default, console]